name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger this action on tags starting with "v"

permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Get previous tag
        id: previousTag
        run: |
          # Get the previous tag
          prev_tag=$(git --no-pager tag --sort=creatordate --merged "${{ github.ref_name }}" | tail -2 | head -1)
          echo "previousTag=$prev_tag" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.previousTag.outputs.previousTag }}
          includeInvalidCommits: true

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}